### ISSUE TITLE
audit befprof and bef2c

### ISSUE THREAD

**Issue by catseye** [catseye/Befunge-93#1]
`befprof` anf `bef2c` probably still have the bugs `bef` used to have with off-by-one errors and such.  They should be tested and fixed.

**Comment by serprex** [comment]
https://github.com/catseye/Befunge-93/pull/3 looks into this

**Comment by cpressey** [comment]
Addressed by #7, which will be released when https://github.com/catseye/Befunge-93/tree/develop-2018-1 is released. Closing.
