### ISSUE TITLE
Typos in the documentation

### ISSUE THREAD

**Issue by j4james** [catseye/Befunge-93#16]
A couple of typos I recently noticed which I thought you might want to patch in the _doc-updates_ branch in case you decide to do something with that in the future.

* In the last paragraph of [The Stack](https://github.com/catseye/Befunge-93/blob/master/doc/Befunge-93.markdown#the-stack) section, you have "If the stack is be empty", which I guess is either meant to be "If the stack is empty" or "If the stack should be empty" (which is what it was in the v1.0 docs).

* In the [opening paragraph](https://github.com/catseye/Befunge-93/blob/master/doc/Befunge-93.markdown#the-basics-of-befunge-93), I believe the word "occassionally" should be spelt "occasionally" (one s).

* In the [Self-Modification](https://github.com/catseye/Befunge-93/blob/master/doc/Befunge-93.markdown#self-modification) section, the word "auxilliary" should be spelt "auxiliary" (one l).

**Comment by cpressey** [comment]
Thanks, I've made those changes. I've elected to avoid "If the stack should be empty" because you can read it as "If the stack ought to be empty" which is... not what is meant.
