### ISSUE TITLE
Commands misnamed in Appendix A

### ISSUE THREAD

**Issue by j4james** [catseye/Befunge-93#5]
In the command summary in Appendix A of the [documentation](https://github.com/catseye/Befunge-93/blob/master/doc/Befunge-93.markdown), the commands `$` `.` and `,` have all been labelled as "pop", but I expect the latter two were probably intended to be something like "output value" and "output character".

Not exactly a major issue, since the actual functionality of each command is clearly explained in the final column, but I thought if you're doing a bit of clean up for the Silver Jubilee, this might be something you want to address.

**Comment by wimrijnders** [comment]
`Silver Jubilee` - Aargh, 25 years already! I was there at the beginning, now I feel old.

**Comment by cpressey** [comment]
@wimrijnders Yes, as you've noticed, that is the explanation for the sudden activity :smiley: You can read more about it here: [Befunge Turns 25 This Year!](http://catseye.tc/article/News#befunge-turns-25-this-year)

@j4james Thanks; not entirely sure what I want to do with the docs yet, but for now, it's fixed on [this feature branch](https://github.com/catseye/Befunge-93/compare/docs-updates).
